# Generated by Django 5.0.4 on 2024-04-05 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_media", "0001_initial"),
        ("home", "0003_homepage_main_image_homepage_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="custom_media.customimage",
            ),
        ),
    ]
